dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
networks:
  default: development
  goerli:
    eth_usd_priceFeed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    verify: True
  mainnet-fork-dev:
    eth_usd_priceFeed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  sepolia:
    eth_usd_priceFeed: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
    verify: True
  development:
    verify: False
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1"
